version: '3'
services:
    hxe:
      image: "saplabs/hanaexpress:2.00.061.00.20220519.1"
      restart: "unless-stopped"
      container_name: "hana_express_edition"
      ports:
        - 39013:39013 
        - 39017:39017 
        - 39041-39045:39041-39045 
        - 1128-1129:1128-1129 
        - 59013-59014:59013-59014
      ulimits:
        nofile:
          soft: 1048576
          hard: 1048576
      hostname: hxehost
      domainname: hxehost.localdomain
#      sysctls:
#        - kernel.shmmax=1073741824
#        - net.ipv4.ip_local_port_range='60000 65535'
#        - kernel.shmall=8388608
      command:
#        - --master-password
#        - HXEHana1
        - --passwords-url
        - file:///data/hxe/masterpassword.json
        - --agree-to-sap-license
      volumes:
      - ./hxe:/hana/mounts
