version: '3'
services:
    hxe:
      image: "saplabs/hanaexpress:2.00.061.00.20220519.1"
      restart: "unless-stopped"
      container_name: "hana_express_edition"
      ports:
        - 49013:49013
        - 49015:49015
        - 49041-49045:49041-49045
        - 1138-1139:1128-1129
        - 59023-59024:59013-59014
        - 49030-49033:49030-49033
        - 51000-51060:51000-51060
        - 53075:53075
      ulimits:
        nofile:
          soft: 1048576
          hard: 1048576
      hostname: hxehost
      domainname: hxehost.localdomain
#      sysctls:
#        - kernel.shmmax=1073741824
#        - net.ipv4.ip_local_port_range='60000 65535'
#        - kernel.shmall=8388608
      command:
#        - --master-password
#        - HXEHana1
        - --passwords-url
        - file:///data/hxe/masterpassword.json
        - --agree-to-sap-license
      volumes:
      - ./hxe:/hana/mounts
